name: evo_ss
description: A support system project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  another_flushbar: ^1.10.28
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  google_fonts: ^2.3.1
  http: ^0.13.4
  image_picker: ^0.8.4+10
  intl: ^0.17.0
  json_annotation: ^4.4.0
  jwt_decode: ^0.3.1
  package_info: ^2.0.2
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/
