POST localhost/evo-ss-api/put HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Accept: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtYUxlbmdrYXAiOiJKZWZmcnkgQW5na2FzYXJpIiwidXNlcm5hbWUiOiJqZWYiLCJ1c2VyTGV2ZWwiOjEsImlkQ2FiYW5nIjpudWxsLCJjYWJhbmciOm51bGwsImlkTG9rYXNpIjpudWxsLCJsb2thc2kiOm51bGwsImlhdCI6MTY0NzA2MTk5MCwiZXhwIjoxNjQ3MDgzNTkwfQ.qhVayijK2S3_imBOXpPLtpLrkWohrlvhEeqOFrGb9Ys

type=updateComplaintStatus
&st=2
&id=1